name: bloomscene
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.9.19
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - basicsr==1.4.2
      - bleach==6.1.0
      - blinker==1.8.2
      - blis==0.7.11
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.18.1
      - cmake==3.29.2
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.2
      - confection==0.1.5
      - configargparse==1.7
      - contexttimer==0.3.3
      - contourpy==1.2.1
      - controlnet-aux==0.0.9
      - cycler==0.12.1
      - cymem==2.0.8
      - dash==2.17.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - decord==0.6.0
      - diffusers==0.26.0
      - distlib==0.3.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - email-validator==2.1.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - facexlib==0.3.0
      - fairscale==0.4.4
      - fastapi==0.111.0
      - fastapi-cli==0.0.3
      - fastjsonschema==2.19.1
      - ffmpy==0.3.2
      - filelock==3.14.0
      - filterpy==1.4.5
      - fire==0.6.0
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - geffnet==1.0.2
      - gfpgan==1.3.8
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.29.0
      - gradio-client==0.16.1
      - grpcio==1.63.0
      - gsplat==0.1.12
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - humanfriendly==10.0
      - icecream==2.1.3
      - identify==2.5.36
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.4.9
      - imgaug==0.4.0
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipython==8.18.1
      - ipywidgets==8.1.2
      - itsdangerous==2.2.0
      - jaxtyping==0.2.29
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.10
      - kaggle==1.6.14
      - kiwisolver==1.4.5
      - langcodes==3.4.0
      - language-data==1.2.0
      - lazy-loader==0.4
      - lightning-utilities==0.11.2
      - lit==18.1.4
      - llvmlite==0.42.0
      - lmdb==1.4.1
      - lpips==0.1.4
      - marisa-trie==1.2.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.0
      - memory-profiler==0.61.0
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numba==0.59.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - onnx==1.16.1
      - onnxruntime==1.18.0
      - open3d==0.18.0
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - orjson==3.10.3
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - peft==0.10.0
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.1
      - plotly==5.22.0
      - plyfile==0.8.1
      - portalocker==2.10.0
      - pre-commit==3.7.1
      - preshed==3.0.9
      - pretty-errors==1.2.25
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py360convert==0.1.0
      - pyarrow==16.1.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyiqa==0.1.11
      - pymeshlab==2022.2.post3
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - python-slugify==8.0.4
      - pytz==2024.1
      - pyyaml==6.0.1
      - realesrgan==0.3.0
      - referencing==0.35.1
      - regex==2024.4.28
      - requests==2.31.0
      - retrying==1.3.4
      - rich==13.7.1
      - rpds-py==0.18.1
      - ruff==0.4.3
      - safetensors==0.4.3
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.11.0
      - setproctitle==1.3.3
      - shapely==2.0.4
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - stack-data==0.6.3
      - starlette==0.37.2
      - streamlit==1.36.0
      - sympy==1.12
      - tabulate==0.9.0
      - tb-nightly==2.18.0a20240708
      - tenacity==8.3.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - text-unidecode==1.3
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tifffile==2024.5.3
      - timm==0.6.7
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.0.1
      - torchac==0.9.3
      - torchaudio==2.0.2
      - torchmetrics==1.4.0
      - torchvision==0.15.2
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.37.2
      - trimesh==4.3.2
      - triton==2.0.0
      - typeguard==2.13.3
      - typer==0.12.3
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - ujson==5.9.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - virtualenv==20.26.3
      - wandb==0.17.5
      - wasabi==1.1.3
      - watchdog==4.0.1
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webdataset==0.2.86
      - webencodings==0.5.1
      - websockets==11.0.3
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - xformers==0.0.22
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.18.1